package com.sales.config;

public class UnAuthorizedPaths {
    public static final  /* Paths which no need to authenticate */
            String[] unAuthorizePaths = {"/admin/auth/login",
            "/admin/auth/login/otp",
            "/admin/auth/sendOtp",
            "/admin/auth/register",
            "/wholesale/auth/login",
            "/wholesale/auth/register",
            "/wholesale/auth/login/otp",
            "/wholesale/auth/sendOtp",
            "/wholesale/auth/register",
            "/webjars/**",
            "/admin/auth/profile/**",
            "/wholesale/auth/profile/**",
            "/admin/store/image/**",
            "/admin/item/image/**",
            "/pg/callback/**",
            "/cashfree/**",
            "/swagger-ui/**",
            "/v3/api-docs/**",
            "/api-docs/**",
            "/plans/**",
            "/wholesale/address/state",
            "/wholesale/address/city/**",
            "/wholesale/store/category/**",
            "/wholesale/store/subcategory/**",
            "/wholesale/auth/validate-otp",
            "/wholesale/plan/all",
            "/admin/auth/profile/**",
            "/index",
            "/chat2",
            "/chat/images/**",
            "/js/**",
            "/css/**",
            "/images/**",
            /* Paths which need to be authenticated but don't need to check in Interceptor or filter due to some different conditions */
            "/wholesale/plan/my-plans",
            "/wholesale/plan/is-active",
            "/pg/pay/**",
            "/wholesale/store/add",
            "/wholesale/auth/detail",
            "/future/plans/**",
            "/wholesale/wallet/**"
    };
}
